site_name: Exonum Documentation
docs_dir: src
theme: flatly
theme_dir: theme
extra_css:
    - css/extra.css
pages:
    - 'Home': 'index.md'
    - 'Anchoring':
        - 'Implementation': 'anchoring-impl.md'
        - 'Specification': 'anchoring-spec.md'
