site_name: Exonum Documentation
docs_dir: src
theme: flatly
theme_dir: theme
extra_css:
    - css/extra.css
pages:
    - 'Home': 'index.md' # Short description of Exonum, documentation and how to use it
    - 'Getting started':
        - 'What is Exonum': 'home/what-is-exonum.md' # What is Exonum 'as a box', from point of view of external developer
        - 'Design overview': 'home/design-overview.md' # How does Exonum look from the inside: nodes, validators, clients, blocks, consensus, genesis block; links to necessary documentation parts.
        - 'Glossary of Terms': 'home/glossary.md'
        - 'Cryptocurrency tutorial':
            - 'Introduction': 'home/cryptocurrency/intro.md'
            - 'Step 1': 'home/cryptocurrency/step1.md'
    - 'Architecture':
        - 'Configuration': 'architecture/configuration.md' # Local configuration - how to roughly configure a node (make it ready to run)
        - 'Storage': 'architecture/storage.md' # Includes blockchain, genesis block, indexes, proofs, etc.
        - 'Transactions': 'architecture/transactions.md' # What is transaction? (purity, sequentual consistency, non-repliability attack, signatures)
        - 'Services': 'architecture/services.md' # Includes guidelines for services
        - 'Clients': 'architecture/clients.md' # How to make Public API communication (both server and client side) 
    - 'Advanced Topics':
        - 'Internode communication': 'advanced/network.md' # How does the network module work: peer discovery, p2p connections
        - 'Serialization': 'advanced/serialization.md' # How the data is serialised and deserialised  to be transfered through the network 
        - 'Merkle index': 'advanced/merkle-index.md'
        - 'Merkle Patricia index': 'advanced/merkle-patricia-index.md'
        - 'Services':
            - 'Configuration': 'advanced/services/configuration.md' # Configuration change service documentation
            - 'BTC Anchoring': 'advanced/services/anchoring.md' # Anchoring service documentation
        - 'Consensus specification':
            - 'Consensus': 'advanced/consensus/consensus.md' # Consensus specification, including proofs
            - 'Leader election': 'advanced/consensus/leader-election.md' # Leader election algorithm specification
            - 'Requests': 'advanced/consensus/requests.md' # Requests specification
            - 'Timeouts adjustment': 'advanced/consensus/timeouts-adjustment.md' # Timeout adjustment module specification
        - 'DoS attacks': 'advanced/dos-attacks.md' # DoS attacks description. How we (are going to) protect the system from it 
        - 'Sandbox testing': 'advanced/sandbox.md' # What is sandbox testing and simple example of one of sandbox tests
    - 'Development':
        - 'Roadmap': 'dev/roadmap.md' # Includes roadmap and features list
        - 'Contributing': 'dev/contributing.md' # How to contribute to Exonum repositories
        - 'License': 'dev/license.md'

