site_name: Exonum Documentation
docs_dir: src
theme: flatly
theme_dir: theme
extra_css:
    - css/extra.css
pages:
    - 'Home':
        - 'Getting started': 'index.md' # How to read this document
        - 'What is Exonum': 'home/what-is-exonum.md' # More technical speech, less marketing bullshit, not too specific 
        - 'Design overview': 'home/design-overview.md' # Nodes, validators, clients, blocks, consensus, genesis block; links
        - 'Glossary of Terms': 'home/glossary.md'
        - 'Cryptocurrency tutorial':
            - 'Introduction': 'home/cryptocurrency/intro.md'
            - 'Step 1': 'home/cryptocurrency/step1.md'
    - 'Architecture':
        - 'Configuration': 'architecture/configuration.md' # Local configuration - how to roughly configurate a node
        - 'Storage': 'architecture/storage.md' # Includes blockchain, genesis block, indexes, proofs, etc.
        - 'Transactions': 'architecture/transactions.md' # What is transaction? (purity, sequentual consistency, non-repliable attack, signatures)
        - 'Services': 'architecture/services.md' # Includes guidelines for services
        - 'Clients': 'architecture/clients.md' # How to make Public API communication (both server and client side) 
    - 'Advanced Topics':
        - 'Internode communication': 'advanced/network.md' 
        - 'Serialization': 'advanced/serialization.md'
        - 'Merkle index': 'advanced/merkle-index.md'
        - 'Merkle Patricia index': 'advanced/merkle-patricia-index.md'
        - 'Services':
            - 'Configuration': 'advanced/services/configuration.md' # Configuration documentation
            - 'BTC Anchoring': 'advanced/services/anchoring.md' # Anchoring documentation
        - 'Consensus specification':
            - 'Consensus': 'advanced/consensus/consensus.md' # Maybe need to split into several parts
            - 'Leader election': 'advanced/consensus/leader-election.md'
            - 'Requests': 'advanced/consensus/requests.md'
            - 'Timeouts adjustment': 'advanced/consensus/timeouts-adjustment.md'
        - 'DoS attacks': 'advanced/dos-attacks.md'
        - 'Sandbox testing': 'advanced/sandbox.md'
    - 'Development':
        - 'Roadmap': 'dev/roadmap.md' # Includes roadmap and features list
        - 'Contributing': 'dev/contributing.md'
        - 'License': 'dev/license.md'

